### PR TITLE
Doing benchmark of basic operators

### PR DESCRIPTION
**Pull request by Oleg-Imanilov**
This is initial version, some more operators need to be added

### CODE REVIEW

**Comment by tomxp411** [comment]
Hi, Oleg. 

I'm glad you wrote this benchmark; I have something similar that I do with prime numbers. Maybe I'll add my test to the end of yours. (It calculates the primes between 1 and 100 using the simple IF X/Y = INT(X/Y) method.)

In the meantime, I found two issues that you might want to address:

I ran the test on a Commodore 64, and the text wraps off the right side just a little. Removing 5 characters in the banner and changing the `30` to `25` on line 32000 fixes this. (There's no down side, since all of your text fits in 40 columns.)

I also found the test results for the first test (the empty FOR) to be inconsistent. At 1000, I first got 6666. Plugging in 2000 for FF gave me 6315. Making that 5000 increased the speed to 6382. Plugging in a much larger number actually dropped the speed to 5952. 

I don't see this kind of swing with the other computations, so I suspected the variation was due to the lack of a line between the FOR and the NEXT. So I added 
`45 REM`
That gave me:
1000 - 4615
2000 - 4615
5000 - 4615

Attached is a version of the program with the changes to make this work in 40 columns and the changes to smooth out the 

[bench1.txt](https://github.com/commanderx16/x16-demo/files/3769304/bench1.txt)

I'm still a little confused by the various "Z" variables. I think you might be overthinking the process there, so I'm going to attempt to refactor that to make that more consistent and get you down to just passing a "start" and "end" time to the subroutine, letting that handle all of the time calculations.

**Comment by tomxp411** [comment]
Okay, this version loses 40-column compatibility, but the time computation is simplified. It uses Z consistently, with no need to assign or re-compute Z0 for each test. It also gives raw timing information for each test (both the actual time and the time with the "empty FOR loop" time removed.)

 
[bench1.txt](https://github.com/commanderx16/x16-demo/files/3769397/bench1.txt)

**Comment by Oleg-Imanilov** [comment]
> but the time computation is simplified. It uses Z consistently, with no need to assign or re-compute Z0 for each test.

NO! When I testing "+" of integers, I want to remove "assigment of integer" time, when I'll test some more complex stuff - I can remove timing of well known sub computed times. 

"+" of small ints - is very fast, but according to your change it is slower than assigment - which is wrong!

**Comment by tomxp411** [comment]
> NO! When I testing "+" of integers, I want to remove "assigment of integer" time, when I'll test some more complex stuff - I can remove timing of well known sub computed times.

Ah, that makes sense. Maybe some comments would help clear that up. 

You still might want to take a look at what I did in lines 1-100 and 32000 to the end.... separating out the jiffy count and adjusted count makes the results easier to understand. As this is a demo, having the clearest possible code really helps.

**Comment by tomxp411** [comment]
In looking at the two tests, the problem with removing the "int assignment" from "int add" is that the bulk of the time is neither the add nor the assignment. It's the parsing of the digits. Are you taking the digit parsing time into account? That would explain why you are using a two digit assignment for A=13 and single digits for A=5+5. 

Here is a version with the adjustments added back in. Rather than re-computing them every time, I used "TE" which is computed in the print subroutine. 

[bench2.txt](https://github.com/commanderx16/x16-demo/files/3769574/bench2.txt)

**Comment by tomxp411** [comment]
Here's the output of your original version and my revised version, so you can compare them.

This is the original version in the Pull Request:
image

And my version:
image

The OP/SEC is based on the the ADJUSTED column, which reflects the addition operations with the parsing and variable assignment time removed.

**Comment by tomxp411** [comment]
And one more update... I think the FLOAT ADD test is also busted. this is because the assignment and the addition tests both use 6 digit values, and so you're testing a total of 12 digits for the addition. 

When I shortened the tests like this:
A = 12.34 
and
A = 1.2+3.4
The tests seem to work more in line with the SMALL INT tests. The FLOAT ADD is exactly 3 cycles faster than the FLOAT ASSIGNMENT. 

This breaks when you go to larger numbers, though. It seems that parsing 123456.123456 takes more than twice as long as parsing 123.456. Interesting.

**Comment by Oleg-Imanilov** [comment]
> And one more update...

Please put your final version, I'll update & we'll continue to add more cases after initial PR merge.

**Comment by tomxp411** [comment]
Here we go. This is as consistent as I can get with the floats. 

I honestly think float addition is probably not worth messing with, since parsing floats is so variable. I'd have to experiment to figure out how to better isolate the addition from the rest of the statement - probably using variables (that really cuts down on the parsing time.)

Anyway, here's my third version:
[bench3.txt](https://github.com/commanderx16/x16-demo/files/3770262/bench3.txt)

**Comment by mist64** [comment]
@tomxp411 If you have changed, can you open a pull request?

**Comment by tomxp411** [comment]
Yes, I'll do a separate PR against the file.

**Pull request merged**
